FROM node:18 AS builder
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:latest
COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
ENV LOCAL_APP_DOMAIN="app.local"
CMD ["sh", "-c", "envsubst '$LOCAL_APP_DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]

