name: Container Deploy

description: Update ECS and deploy container

inputs:
  ecs-cluster:
    required: true
    description: ECS cluster
  ecs-service:
    required: true
    description: ECS
  task-definition:
    required: true
    description: Task definition
  container-name:
    required: true
    description: Container name
  container-image:
    required: true
    description: Container image

runs:
  using: composite
  steps:
    - name: get task definition
      run: |
        aws ecs describe-task-definition --task-definition "${TASK_DEFINITION}" \
        --query taskDefinition --output json > "${RUNNER_TEMP}"/task-def.json
      env:
        TASK_DEFINITION: ${{ inputs.task-definition }}
      shell: bash
    - name: fix task definition
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      id: render
      with:
        task-definition: ${{ runner.temp }}/task-def.json
        container-name: ${{ inputs.container-name }}
        image: ${{ inputs.container-image }}
    - name: update task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        cluster: ${{ inputs.ecs-cluster }}
        service: ${{ inputs.ecs-service }}
        task-definition: ${{ steps.render.outputs.task-definition }}

